name: DevOps Dashboard CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        # This tells the terminal to 'cd backend' before running npm install
        run: npm install
        working-directory: ./backend

      - name: Verify Files (Debug Step)
        # This will list files so we can see what the runner sees
        run: ls -R

      - name: Force fail for testing
        run: exit 1
